@baseUrl = http://localhost:3000

### RecadosModuleGetAll
# @name RecadosModuleGetAll
GET {{baseUrl}}/recados
Authorization: Bearer SeuTokenAqui

### RecadosModuleGetOne
# @name RecadosModuleGetOne
GET {{baseUrl}}/recados/1

### RecadoModulePost
# @name RecadoModulePost
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "Conteudo do recado novo",
    "deId": 1,
    "paraId": 2
}

### RecadoModulePatch
# @name RecadoModulePatch
PATCH {{baseUrl}}/recados/1
Content-Type: application/json

{
    "texto": "Conteudo atualizado",
    "lido": true
}

### RecadoModuleDelete
# @name RecadoModuleDelete
DELETE {{baseUrl}}/recados/1


### Pessoas
# @name PessoaModulePost
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
    "name": "julia",
    "email": "julia@example.com",
    "password": "123456"
}

### PessoasModuleGet
# @name PessoaModuleGetAll
GET {{baseUrl}}/pessoas

### PessoaModuleGetOne
# @name PessoaModuleGetOne
GET {{baseUrl}}/pessoas/3

### PessoaModuleDelete
# @name PessoaModuleDelete
DELETE {{baseUrl}}/pessoas/3