@baseUrl = http://localhost:3000

### RecadosModuleGet

# @name RecadosModuleGet
GET {{baseUrl}}/recados/213

### RecadoModulePost
# @name RecadoModulePost
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "title" : "Recado Novo",
    "content" : "Conteudo do recado novo" 
}


### Pessoas
# @name PessoaModulePost
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
    "name": "gabriel",
    "email": "gabriel@example.com",
    "password": "123456"
}